export const SET_TICKET_ROOM_DETAIL = 'SET_TICKET_ROOM_DETAIL';

export const BOOK_TICKET = 'BOOK_TICKET';

export const COMPLETE_BOOK_TICKET = 'COMPLETE_BOOK_TICKET';

export const MOVE_TAB_AFTER_BOOKING = 'MOVE_TAB_AFTER_BOOKING';